//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldStressMapTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldStressMapTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Williams,-54.9333,-67.6167
        ///Ushuaia,-54.79,-68.31
        ///Grytviken,-54.2806,-36.508
        ///Rio Grande,-53.7914,-67.699
        ///Punta Arenas,-53.165,-70.94
        ///R�o Verde,-52.65,-71.4666
        ///Puerto Natales,-51.7183,-72.5117
        ///Stanley,-51.7,-57.85
        ///28 de Noviembre,-51.65,-72.3
        ///R�o Gallegos,-51.6333,-69.2166
        ///El Calafate,-50.3333,-72.3
        ///Comondante Luis Piedrabuena,-49.9745,-68.9035
        ///Puerto San Juli�n,-49.3,-67.7167
        ///Gobernador Gregores,-48.7666,-70.25
        ///Villa O&apos;Higgins,-48.4679,-72.56
        ///Puerto Deseado,-47.75,-65.9
        ///Cochrane,-47.26 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string citiesALL {
            get {
                return ResourceManager.GetString("citiesALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubai,25.258172,55.304717
        ///Kabul,34.516667,69.183333
        ///Yerevan,40.1811111,44.5136111
        ///Luanda,-8.836804,13.233174
        ///Cordoba,-31.413496,-64.181052
        ///Rosario,-32.946818,-60.639317
        ///Vienna,48.2,16.366667
        ///Adelaide,-34.928661,138.598633
        ///Brisbane,-27.47101,153.024292
        ///Melbourne,-37.813938,144.963425
        ///Perth,-31.95224,115.861397
        ///Sydney,-33.861481,151.205475
        ///Baku,40.395278,49.882222
        ///Dhaka,23.7230556,90.4086111
        ///Khulna,22.8,89.55
        ///Brussels,50.833333,4.333333
        ///Ouagadougou,12.3702778,-1.5247222
        ///Sofia,42.6833333,23.3166667
        ///Belém,-1.45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string citiesMAJOR {
            get {
                return ResourceManager.GetString("citiesMAJOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometry,geometry_vertex_count,OBJECTID,ISO_2DIGIT,Shape_Leng,Shape_Area,Name,import_notes,Google requests
        ///&quot;&lt;Polygon&gt;&lt;outerBoundaryIs&gt;&lt;LinearRing&gt;&lt;coordinates&gt;1.44583614083,42.6019451433,0 1.73860914641,42.6163911858,0 1.72360906008,42.5094360893,0 1.45152728546,42.4462450888,0 1.44583614083,42.6019451433,0&lt;/coordinates&gt;&lt;/LinearRing&gt;&lt;/outerBoundaryIs&gt;&lt;/Polygon&gt;&quot;,5,1,AD,0.836259,0.036910,Andorra,,
        ///&quot;&lt;Polygon&gt;&lt;outerBoundaryIs&gt;&lt;LinearRing&gt;&lt;coordinates&gt;55.1991632424,22.6997181535,0 52.5833273251,22.9388910674,0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countryBoundaries {
            get {
                return ResourceManager.GetString("countryBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID,SITE,LAT,LON,AZI,TYPE,DEPTH,QUALITY,REGIME,LOCALITY,COUNTRY,DATE,TIME,NUMBER,SD,METHOD,S1AZ,S1PL,S2AZ,S2PL,S3AZ,S3PL,MAG_INT_S1,SLOPES1,MAG_INT_S2,SLOPES2,MAG_INT_S3,SLOPES3,PORE_MAGIN,PORE_SLOPE,MAG_TYPE,EQ_MAG,MOM,MOM_EXP,EQ_AVG,TOT_LEN,SD_WEIGHT,SAMP_INT,TOP,BOT,NO_MAG_VEN,YOUNG,POISSON,ROCK,AGE,RATIO,DIPAZ,DIP,REF1,REF2,REF3,REF4,COMMENT,LAST_MOD,PLATE,BOUNDARY,DIST,PBE,NEW,ISO,,,,,
        ///wsm00001,TU31,40.300,28.230,100,FMS,14.00,C,NF,,Turkey,19641006,14:31:23,,,,190,85,100,0,10,5,,,,,,,,,Mb,6.0,,,,,,,,,,, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wsm2016 {
            get {
                return ResourceManager.GetString("wsm2016", resourceCulture);
            }
        }
    }
}
